DMGT-TECH/the-usher-server

docs/CONTRIBUTORS.md
=> Contributor List - adding a couple names

database/package-lock.json, database/package.json, server/package-lock.json, server/package.json
=> chore: prepare release

database/package-lock.json, database/package.json, docs/INSTALL.md, server/package-lock.json
Update the package name of the database package to conform to the new naming convention of this repo/package.
=> fix: update db package name

mockidentityprovider/src/api_endpoints/endpoint_oauth_token.js, server/src/api_endpoints/endpoint_self_refresh_token.js, server/src/api_endpoints/endpoint_self_token.js, server/src/security_layer/jwt_signature_validator.js
This PR fixes a few small, code tidy items identified by lgtm site.
Closes NA
=> fix: small code tidy

.dockerignore, .gitignore, docker-compose-ci.yml, docker-compose.yml, server/package-lock.json
Update docker containers to newer image versions, docker compose to `3.8`
Closes NA
=> fix: update containers to newer versions

database/package-lock.json, database/package.json, server/package-lock.json, server/package.json
Small lib updates to resolve a few security issues.
Closes #
=> chore: small lib updates

docs/INSTALL.md, server/.env.sample, server/src/security_layer/jwt_signature_validator.js, server/the-usher.js
Update to make the `THEUSHER_AUD_CLAIMS` server parameter optional.
Closes #20
=> feat: #20 update logic for aud verification optional

mockidentityprovider/package-lock.json, mockidentityprovider/package.json, mockidentityprovider/src/utils/keystore.js, server/the-usher-openapi-spec.yaml
* Small updates to the Open API spec, mainly in the `Info` object
* Update libs in the mockidentityserver project and remove unused libs
Closes #
=> chore: update mock server, clean open api doc

.github/workflows/publish-package.yml, .github/workflows/render-diagrams.yaml, .github/workflows/run-tests.yaml
Quick PR to update GitHub actions steps to latest versions.
Closes #
=> chore: update gh actions versions

database/package-lock.json, database/package.json, docker-compose-ci.yml, docker-compose.yml, docs/CONTRIBUTING.md, docs/DATAMODEL.md, docs/INSTALL.md, docs/QUICKSTART.md, mockidentityprovider/package-lock.json, mockidentityprovider/package.json, server/package-lock.json, server/package.json, server/src/api_endpoints/endpoint_invalidate_session.js, server/test/endpoint_invalidate_session.test.js, server/test/security_layer_issuer_aliases.test.js, server/the-usher-openapi-spec.yaml
Updates a number of dependencies in server and database projects. The following libs were specifically not fully updated to minimize the changeset and be resolved in separate PRs. 
```
Package    Current  Wanted  Latest  Location                Depended by
jwks-rsa     2.1.5   2.1.5   3.0.0  node_modules/jwks-rsa   server
node-fetch    2.6.7   2.6.7   3.3.0  node_modules/node-fetch  server
oas-tools    2.1.8   2.1.8   3.0.0  node_modules/oas-tools  server
```
```
Package    Current  Wanted  Latest  Location                Depended by
oas-tools    2.2.2   2.2.2   3.0.0  node_modules/oas-tools  mockidentityprovider
```
Closes #46
=> feat: update server and database libs 

database/package-lock.json, database/package.json, mockidentityprovider/package-lock.json, mockidentityprovider/package.json, server/package-lock.json, server/package.json, server/test/endpoint_invalidate_session.test.js
* Prepare the v1.6.0 release
* Update jwks-rsa, helmet to latest
* Update mocha to latest
Closes NA
=> chore: prepare 1.6, lib updates

database/layer/admin-personarole.js
Closes : https://github.com/DMGT-TECH/the-usher-server/issues/64
As a contributor, I've taken comprehensive measures to address the issues highlighted in the original query. This PR underscores our commitment to maintaining data integrity and operational robustness within the application.
This enhancement represents a proactive step toward ensuring the precise deletion of personaroles while upholding the highest standards of data management.
Thank you for considering this pull request.
Sahil Jain.
=> Bug: Corrected DELETE Query for Accurate Personaroles Deletion

database/layer/admin-personarole.js, database/test/db-insert.test.js
* Add test coverage for `deletePersona` function, related to #64 
* Fix query from #65 to remove quotes around named parameters
Closes #64
=> chore: add test for deletePersona

.dockerignore, .github/workflows/publish-package.yml, .github/workflows/run-tests.yaml, database/package-lock.json, database/package.json, docker-compose-ci.yml, docker-compose.yml, mockidentityprovider/package-lock.json, mockidentityprovider/package.json, server/package-lock.json, server/package.json, server/the-usher-openapi-spec.yaml
* Bump patch version to `1.6.1` for new patch release
* Update node version to 16 for docker and GitHub Action tests
* Add missing `summary` attributes to a few Open API methods for future Open API Spec linting
Closes #
=> chore: prepare 1.6.1 release

.github/workflows/codeql.yml, .github/workflows/publish-package.yml, .github/workflows/render-diagrams.yaml, .github/workflows/run-tests.yaml, README.md, database/README.md, docker-compose-ci.yml, docker-compose.yml, docs/DEVELOP.md, docs/QUICKSTART.md, mockidentityprovider/package-lock.json, mockidentityprovider/package.json, server/the-usher-openapi-spec.yaml
* Upgrade postgres version from 12 to 13
* Make use of docker compose v2 files, use `docker compose` (space, not dash)
* Use `include` to reduce duplicate container definitions between the two compose files
* Update docs with the above changes
Closes #
=> UNTRACKED: chore: update pg version

database/constant/PgErrorCodes.js, database/knexfile.js, database/layer/admin-persona.js, database/layer/knex.js, database/package.json, database/test/db-admin-persona.test.js, database/utils/pgErrorHandler.js, server/package.json, server/src/api_endpoints/personas/persona.js, server/test/endpoint_admin_personas.test.js, server/the-usher-openapi-spec.yaml
Implement POST:/personas- Admin APIs
- [feat: topics/k1ch/ introduce POST/personas](https://github.com/DMGT-TECH/the-usher-server/commit/189f6528d8807b3fe0466e347fc8dc006ca5c9f7)
- [feat: topics/k1ch/POST-personas/error handling](https://github.com/DMGT-TECH/the-usher-server/commit/f7ba723f2975d2cc3243be595ade30caa8009218)
- [chore: topics/k1ch/POST-personas/db-layer and API tests](https://github.com/DMGT-TECH/the-usher-server/pull/79/commits/8b8207487a208ce60002fd117c212aa207011951)
- [chore: topics/k1ch/POST-personas/code style clean up](https://github.com/DMGT-TECH/the-usher-server/pull/79/commits/7a0ff7277a1877bdee3c3b40b14961a2c01f7e40)
<details open>
<summary>Test results!</summary>
</details>
<details>
<summary>OAS POST:/personas</summary>
</details>
Remaining: 
❤️ Please review …
=> Topics/k1ch/Admin APIs -  POST:/personas

database/layer/admin-persona.js, database/layer/knex.js, database/test/db-admin-persona.test.js, server/src/api_endpoints/personas/permissions.js, server/src/api_endpoints/personas/utils.js, server/test/endpoint_admin_personas_permissions.test.js, server/the-usher-openapi-spec.yaml
- [feat: topics/k1ch/ introduce get/personas-permissions](https://github.com/DMGT-TECH/the-usher-server/pull/80/commits/179fdaaa80121b27fb02e08d1d67f60add672546)
- [chore: topics/k1ch/admin-get-persona-permissions/add tests](https://github.com/DMGT-TECH/the-usher-server/pull/80/commits/eb1f814e89c171c7712c197d6852d0051cac4e54)
<details>
<summary>OAS update</summary>
</details>
<details open>
<summary>Test results!</summary>
</details>
Remaining: 
Partially closes https://github.com/DMGT-TECH/the-usher-server/issues/60
=> Topics/k1ch/ introduce get/personas-permissions

database/layer/admin-personarole.js, database/test/db-admin-personaroles.test.js, server/src/api_endpoints/personas/roles.js, server/test/endpoint_admin_personas.test.js, server/test/endpoint_admin_personas_permissions.test.js, server/test/endpoint_admin_personas_roles.test.js, server/test/endpoint_self_clients.test.js, server/test/endpoint_self_roles.test.js, server/the-usher-openapi-spec.yaml
- [feat: topics/k1ch/admin-get-personas-roles/introduce Admin](https://github.com/DMGT-TECH/the-usher-server/commit/b15e4fb1ba1481c6f678cba7d78b7441b9f663d4)
- [chore: topics/k1ch/admin-get-personas-roles/ API & DB tests](https://github.com/DMGT-TECH/the-usher-server/commit/752a8bf924ce98decd0bae83c1f1c45259c7b443)
<details>
<summary>OAS Update: </summary>
</details>
<details open>
<summary>New tests: </summary>
</details>
Relates to #58
=> Topics/k1ch/admin GET: /personas/{persona_key}/roles

database/layer/admin-personapermission.js, database/layer/admin-personarole.js, database/test/db-admin-personapermissions.test.js, database/test/db-admin-personaroles.test.js, server/src/api_endpoints/personas/permissions.js, server/src/api_endpoints/personas/roles.js, server/src/api_endpoints/personas/utils.js, server/test/endpoint_admin_personas_permissions.test.js, server/test/endpoint_admin_personas_roles.test.js, server/the-usher-openapi-spec.yaml
- [feat: topics/k1ch/admin-post-personas-roles/ introduce API](https://github.com/DMGT-TECH/the-usher-server/commit/c994a346e6d836ca131ef1305223b492a49bded3)
- [chore: topics/k1ch/admin-post-personas-permissions/checkPersonaPermis…](https://github.com/DMGT-TECH/the-usher-server/pull/88/commits/855c015fded52efc89d7a0976f5f1875f48b1182)
- [chore: topics/k1ch/admin-post-personas-roles/add API and DB tests](https://github.com/DMGT-TECH/the-usher-server/commit/bb263692cb768b0d247c6217b305d3d536256d13)
- [chore: topics/k1ch/admin-put-personas-roles/post -> put](https://github.com/DMGT-TECH/the-usher-server/pull/88/commits/68711372351f4376dbe4740914eca83c8f286fbc)
- [chore: topics/k1ch/admin-put-personas-permissions/post -> put](https://github.com/DMGT-TECH/the-usher-server/pull/88/commits/8ee4ad …
=> Topics/k1ch/admin PUT:/personas/{persona_key}/roles

server/src/api_endpoints/personas/persona.js, server/test/endpoint_admin_personas.test.js, server/the-usher-openapi-spec.yaml
- [feat: topics/k1ch/ Admin GET:/personas/{key}](https://github.com/DMGT-TECH/the-usher-server/commit/b1a9ee5dd40b39d07a092f91f3a4b581ea205d4a)
<details open>
<summary> OAS changes:</summary>
</details> 
<details open>
<summary>Added tests:</summary>
</details> 
Closes #59
=> Topics/k1ch/ Admin GET:/personas/{persona_key}

database/package-lock.json, database/package.json, server/package-lock.json, server/package.json
- [chore: k1ch/update libs and package-lock files](https://github.com/DMGT-TECH/the-usher-server/commit/7d44baea3c8191e90c075c7bf71bd6916151417f)
Closes #
=> Chore: k1ch/update libs and package-lock files

database/package-lock.json, database/package.json, server/package-lock.json, server/package.json
- [chore: topic/k1ch/ bump up package version to: v2.0.0](https://github.com/DMGT-TECH/the-usher-server/commit/6925a12b44eb6fba75fc7da0f05268ad8ccf0ba1)
- [chore: topic/k1ch/release-v2.0.0/update supported node engines](https://github.com/DMGT-TECH/the-usher-server/commit/ee1eb4ef51fa9a28d6aba4f79806022003a0d3b5)
Closes #
=> Topic/k1ch/ bump up package version to: v2.0.0

database/migrations/20240220125255_86-perms-clients-fk.js, database/package-lock.json, database/package.json, server/package-lock.json, server/package.json
* Add foreign key for permissions clientkey to reference clients table
* Update `dotenv` to `16.4.5` to resolve bug in lib
Closes #86
=> chore: add fk to permissions table for client key

.github/workflows/codeql.yml
* Update codeql GitHub actions to v3, this will resolve the node v16 deprecation notices
Closes #
=> chore: update codeql workflow file

database/layer/view-select-relationships.js, database/package-lock.json, database/package.json, server/package-lock.json, server/package.json, server/src/api_endpoints/endpoint_self_token.js
Optimize the SQL query which was introduced in #98
- [chore: topic/k1ch/sql-optimization-selectTenantPersonaClients](https://github.com/DMGT-TECH/the-usher-server/commit/11b8506c8923baadc2c61e6b6a48f3cd2cf988c2)
Performance before optimization: `~4.4 s`
Performance after optimization: `~0.045 s`  (`~99%` improvement)
Closes #
=> Topic/k1ch/ SQL optimization: selectTenantPersonaClients

database/layer/admin-personapermission.js, database/layer/admin-personarole.js, database/test/db-admin-permissions.test.js, database/test/db-admin-persona.test.js, database/test/db-admin-personapermissions.test.js, database/test/db-admin-personaroles.test.js, database/test/db-cascade-delete.test.js, database/test/db-client.test.js, database/test/db-insert.test.js, database/test/db-keys.test.js, database/test/db-persona.test.js, database/utils/pgErrorHandler.js, server/src/api_endpoints/personas/persona.js, server/test/endpoint_admin_personas.test.js, server/test/endpoint_admin_personas_permissions.test.js, server/test/endpoint_admin_personas_roles.test.js, server/test/endpoint_clients.test.js, server/test/endpoint_errors.js, server/test/endpoint_invalidate_session.test.js, server/test/endpoint_jwks.test.js, server/test/endpoint_self_clients.test.js, server/test/endpoint_self_permissions.test.js, server/test/endpoint_self_refresh_token.test.js, server/test/endpoint_self_roles.test.js, server/test/endpoint_self_token.test.js, server/test/root.test.js, server/test/security_layer_issuer_aliases.test.js, server/test/security_layer_signature_validation.js, server/test/utils/token-utils.test.js
* Add test cases to cover the database functions that are using the knex `ignore` and `returning` functions together. Also updated the function comment to be explicit in what is currently happening. 
Closes #
=> UNTRACKED(chore): add tests for ignore use case

.github/workflows/publish-package.yml, .github/workflows/run-tests.yaml, database/layer/admin-session.js, database/package-lock.json, database/package.json, database/test/db-cascade-delete.test.js, database/test/db-insert.test.js, docker-compose-ci.yml, docker-compose.yml, mockidentityprovider/package-lock.json, mockidentityprovider/package.json, server/package-lock.json, server/package.json
* Remove `uuid` library and use native `crypto` function as replacement
* Update few misc libs
* Update GitHub and Docker images to node v20
Closes #
=> UNTRACKED(chore): Remove uuid lib and nodejs version

database/package-lock.json, database/package.json, server/package-lock.json, server/package.json, server/the-usher-openapi-spec.yaml
- [chore: untracked/k1ch/bump-version-to-2.0.2](https://github.com/DMGT-TECH/the-usher-server/pull/114/commits/15cb0e9e96501a074b931dbe02de6eff2a0ac757)
Closes #
=> UNTRACKED /k1ch/bump-version-to-2.0.2

database/package-lock.json, database/package.json, server/package-lock.json, server/package.json, server/the-usher-openapi-spec.yaml
- [chore untracked/k1ch/bump version to v2.1.0](https://github.com/DMGT-TECH/the-usher-server/commit/10d4c938e5c47b366d4c6915475eb8d985807ef3)
Closes #
=> UNTRACKED /k1ch/bump version to v2.1.0

database/layer/admin-rolepermissions.js, database/test/db-admin-rolepermissions.test.js, server/src/api_endpoints/roles/permissions.js, server/src/api_endpoints/roles/utils.js, server/test/endpoint_admin_roles_permissions.test.js, server/the-usher-openapi-spec.yaml
- [feat: k1ch / introduce PUT:/roles/{role_key}/permissions](https://github.com/DMGT-TECH/the-usher-server/commit/2d1b49af81e5146cdc032519a26e305512322acd)
- [chore: k1ch/ add tests to admin-rolepermissions db layer](https://github.com/DMGT-TECH/the-usher-server/pull/132/commits/d7f3cf55636705158eed3f771ddccd1ea9b628d0)
- [chore: k1ch / add tests for PUT:/roles/{role_key}/permissions](https://github.com/DMGT-TECH/the-usher-server/pull/132/commits/1d755f4a5f9d52054a4a75bbb492f1d1caa9c701)
Partially completes #106
=> Topic /k1ch/ introduce API `PUT:/roles/{role_key}/permissions`

database/package-lock.json, database/package.json, server/package-lock.json, server/package.json, server/the-usher-openapi-spec.yaml
- [chore: k1ch/bump version to v2.4.0](https://github.com/DMGT-TECH/the-usher-server/commit/01739b7234302a4d7646ba9d45e9f664a5a956e7)
Closes #
=> Topic/ k1ch / bump version to v2.4.0

database/package-lock.json, database/package.json, server/package-lock.json, server/package.json, server/the-usher-openapi-spec.yaml
- [chore: k1ch/ bump version to 2.5.0](https://github.com/DMGT-TECH/the-usher-server/commit/a179ba11d3041a52d54d110e306e8ea0d077890b)
Closes #
=> Chore / k1ch / bump version to 2.5.0

database/layer/admin-tenant.js, database/test/db-admin-tenant.test.js, server/src/api_endpoints/tenants/index.js, server/test/endpoint_admin_tenants.test.js, server/the-usher-openapi-spec.yaml
- [feat: topic / k1ch / introduce GET:/tenants](https://github.com/DMGT-TECH/the-usher-server/pull/138/commits/da2cc1f25a860f8ae723d62503596c92c0c5e12a)
Partially completes https://github.com/DMGT-TECH/the-usher-server/issues/139
=> Topic / k1ch / Introduce `GET:/tenants`

database/package-lock.json, database/package.json, server/package-lock.json, server/package.json, server/the-usher-openapi-spec.yaml
=> Chore / k1ch / bump-version-2.6.0

database/layer/admin-personarole.js, database/package-lock.json, database/package.json, server/package-lock.json, server/package.json, server/the-usher-openapi-spec.yaml
- [chore: k1ch / include timestamps for GET:/personas/{key}/roles](https://github.com/DMGT-TECH/the-usher-server/commit/99f12bd6f51803e2f7533370d262842bd869f321)
Closes #
=> Topic / k1ch / include timestamp for `GET:/personas/{key}/roles`

database/layer/admin-permission.js, database/layer/admin-tenant.js, database/test/db-cascade-delete.test.js, database/test/db-insert.test.js
* Remove `PgPool` from a few more database functions and replace with knex. 
Closes #
=> chore: remove pgpool from few functions

database/package-lock.json, database/package.json, mockidentityprovider/package-lock.json, mockidentityprovider/package.json, server/package-lock.json, server/package.json
=> chore: minor library updates

database/test/db-admin-tenant.test.js, server/src/api_endpoints/tenants/index.js, server/test/endpoint_admin_tenants.test.js, server/the-usher-openapi-spec.yaml
* Add `POST /tenants` API and associated open api spec.
Relates to #139
=> feat: add POST tenants API
